name: Deploy to Render

on:
  push:
    branches:
      - main  # ✅ Fixed: `-main` → `- main` (space required)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # ✅ Optional: Checks out the repository (if needed)
        uses: actions/checkout@v3

      - name: Deploy to Render
        run: | 
          curl -X POST ${{ secrets.DEPLOYMENT_HOOK_URL }}  # ✅ Secure the URL using GitHub Secrets
